package util;

public enum Enum {
    OK,

    EMAIL_EMPTY,
    EMAIL_TOO_LONG,
    EMAIL_INVALID_FORMAT,
    EMAIL_INVALID_CHAR,
    EMAIL_DUPLICATE,

    PASSWORD_EMPTY,
    PASSWORD_TOO_LONG,
    PASSWORD_INVALID_CHAR,

    NAME_EMPTY,
    NAME_TOO_LONG,
    NAME_INVALID_CHAR,
    NAME_DUPLICATE,

    STONE_STYLE_INVALID,
    
    DUPLICATE,
    UNKNOWN_ERROR
}
